name: ytory
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_splash_screen: ^1.0.0+1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  progress_dialog: ^1.2.4
  grafpix: ^1.2.8
  flushbar: ^1.10.4
  awesome_dialog: ^1.1.3
  firebase_messaging: ^6.0.16
  photo_manager: ^0.5.3+1
  permission_handler: ^5.0.1+1
  somedialog: ^1.0.1
  simple_image_crop: ^0.1.3
  video_trimmer: 
    path: ./modified_lib/video_trimmer-0.2.4
  video_player: ^0.10.11+2
  animator: ^1.0.0+5
  content_placeholder: ^0.1.0
  image_picker: ^0.6.7+4
  camera: ^0.5.8+2
  wakelock: ^0.1.4+2
  path_provider: ^1.6.11
  geolocator: ^5.3.2+2
  flutter_staggered_grid_view: ^0.3.0
  transparent_image: ^1.0.0
  flutter_video_compress: ^0.3.7+8
  fancy_shimmer_image: ^1.0.1
  cached_network_image: ^2.2.0+1
  timeago: ^2.0.26
  expand_widget: ^1.0.0+1
  uuid: ^2.2.0
  flutter_switch:
    path: ./modified_lib/flutter_switch-0.1.0
  giphy_picker:
    path: ./modified_lib/giphy_picker-1.0.4

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

 
  assets:
    - assets/splash_icon.png
    - assets/empty.jpg
    - assets/profilePhoto.png
    - assets/video_dialog.jpg
    - assets/empty_story.png
    - assets/empty_chat.jpg
    
    - assets/icons/any.png
    - assets/icons/male.png
    - assets/icons/female.png
    - assets/icons/left-arrow.png
    - assets/icons/eye_open.png
    - assets/icons/eye_close.png
    - assets/icons/diary.png
    - assets/icons/bell.png
    - assets/icons/chat.png
    - assets/icons/user.png
    - assets/icons/more.png
    - assets/icons/notification.png
    - assets/icons/add.png
    - assets/icons/export.png
    - assets/icons/plus.png
    - assets/icons/camera.png
    - assets/icons/forward.png
    - assets/icons/done.png
    - assets/icons/play.png
    - assets/icons/cut.png
    - assets/icons/close.png
    - assets/icons/crop.png
    - assets/icons/cropcut.png
    - assets/icons/from.png
    - assets/icons/video-camera.png
    - assets/icons/up.png
    - assets/icons/plane.png
    - assets/icons/gif.png
    - assets/icons/clear.png
    - assets/icons/search.png
    - assets/icons/timeago.png
    - assets/icons/chat_user.png
    - assets/icons/add-user.png
    - assets/icons/gallery.png
    - assets/icons/chat_gif.png
    - assets/icons/chat_image.png
    - assets/icons/chat_video.png
    
    - assets/icons/upload-to-cloud.gif
    - assets/icons/fidget-spinner.gif
    - assets/icons/add-cloud.gif
    
    - assets/icons/like.png
    - assets/icons/like_light.png
    - assets/icons/fire.png
    - assets/icons/fire_light.png
    - assets/icons/heart.png
    - assets/icons/heart_light.png
    - assets/icons/heart_light.png
    - assets/icons/cheers.png
    - assets/icons/cheers_color.png
    - assets/icons/fuck.png
    - assets/icons/fuck_color.png

